# NOTE: update this with your service name
service: bmnns-api

resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-webpack
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-east-1
  environment:
    tableName: UserOrdersTable
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource: 
        - "arn:aws:dynamodb:us-east-1:*:*"

functions:
  ### Funções para os pedidos ###
  createOrder:
    handler: functions/order/createOrder.main
    events:
      - http:
          path: order
          method: post
          cors: true
          authorizer: aws_iam
  sendOrderEmail:
    handler: functions/order/sendOrderEmail.main
    events:
      - http: 
          path: sendOrder
          method: get
          cors: true
          authorizer: aws_iam
  listOrders:
    handler: functions/order/listOrders.main
    events:
      - http: 
          path: listOrders
          method: get
          cors: true
          authorizer: aws_iam
 

